### PR TITLE
Add harbor_usergroup resource & data source

### PR DESCRIPTION
**Pull request by burdzwastaken**
Also included a .gitignore and some acceptance tests for the data source. I am working on finishing the testing for the resource now.

### CODE REVIEW

**Comment by sandhose** [comment]
Hey, thanks for this PR!

Code looks good, unfortunately I don't have much time right now to test it ; I'll do it tomorrow

**Comment by burdzwastaken** [comment]
@sandhose any chance you can take a look at this PR?

**Comment by sandhose** [comment]
I tried to setup a Harbor instance setup with LDAP auth but I can’t get it to work. They seem to rely on Active Directory filters for groups (see <https://github.com/goharbor/harbor/blob/551a956fcbfe0ed9cb5abb0d3fb6aced9999c49b/src/common/utils/ldap/ldap.go#L447>) and I don’t have a Windows Server available to test.

What kind of setup do you have? Besides this the code looks OK so if you tested it and works for you I’ll merge this

**Comment by sandhose** [comment]
I managed to setup Harbor locally with LDAP used as auth to test.

The acceptance tests are failing though:

```
=== RUN   TestAccHarborUserGroupDataSource_Basic
--- FAIL: TestAccHarborUserGroupDataSource_Basic (0.11s)
    testing.go:568: Step 0 error: errors during apply:

        Error: [POST /usergroups][409] postUsergroupsConflict

          on /var/folders/bj/zh9r2wl538z7yxcqxr0zjzsm0000gn/T/tf-test051120165/main.tf line 2:
          (source code not available)


=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProviderParameters
--- PASS: TestProviderParameters (0.00s)
=== RUN   TestAccHarborUserGroup_Basic
--- FAIL: TestAccHarborUserGroup_Basic (0.08s)
    testing.go:568: Step 0 error: errors during apply:

        Error: [POST /usergroups][409] postUsergroupsConflict

          on /var/folders/bj/zh9r2wl538z7yxcqxr0zjzsm0000gn/T/tf-test792580511/main.tf line 2:
          (source code not available)


FAIL
FAIL    github.com/sandhose/terraform-provider-harbor/harbor    0.557s
FAIL
make: *** [testacc] Error 1
```

In the Harbor logs I'm getting this:

```
Oct 15 21:30:42 172.21.0.1 core[1312]: 2019-10-15T21:30:42Z [ERROR] [/common/api/base.go:68]: POST /api/usergroups failed with error: {"code":400,"message":"LDAP Group DN is not found: DN:"}
```

Shouldn't the resource set the `ldap_group_dn`? It is marked [as computed](https://github.com/sandhose/terraform-provider-harbor/pull/3/files#diff-4d2477b9ea55b14a1bdfc10f6b385f39R35-R38)

**Comment by burdzwastaken** [comment]
hey @sandhose thanks for the prompt response. my current setup is using [FreeIPA](https://www.freeipa.org/page/Main_Page) with the following configuration:
```
  url: "ldaps://fed-ipa.domain.io"
  searchPassword: "hunter2"
  baseDN: "cn=users,cn=accounts,dc=domain,dc=io"
  searchDN: "uid=harbor,cn=users,cn=accounts,dc=domain,dc=io"
  filter: "(objectClass=person)"
  uid: "uid"
  scope: "2"
  timeout: "5"
  verifyCert: "True"
  groupBaseDN: "cn=groups,cn=accounts,dc=domain,dc=io"
  groupFilter: "(objectClass=groupofnames)"
  groupAdminDN: "cn=harbor,cn=groups,cn=accounts,dc=domain,dc=io"
  groupScope: "2"
```
I believe I made an error with the schema for the data source as it is not computed and needs to be supplied. example resource:
```
resource "harbor_usergroup" "provider_resource_group_type_ldap" {
	group_name = "terraform_provider_group_creation_test"
	group_type = 1
	ldap_group_dn = "cn=test-group,cn=groups,cn=accounts,dc=domain,dc=io"
}
```
I can make another commit to fix that.

**Comment by burdzwastaken** [comment]
@sandhose sorry finally had time to review this. `ldap_group_dn` is only computed in the dataSource. within the [resource](https://github.com/sandhose/terraform-provider-harbor/pull/3/files#diff-894b30c608fba246b55f2a5999252e0cR37-R40) it is marked as optional. I am not sure if that is the best way to handle it.

**Pull request closed without merging**
